Homework17
Melifarowow/jsexpert1 pull request #13
Opened 2017-08-15 10:01 UTC by Melifarowow

Дз реализовано в новых компонентах / сервисах. Кнопка "изменить" и форма добавления нового фильма отображается на главной странице и "/popular"

2017-08-15 20:18 UTC, fullstackdb requested changes
незначительные изминения запрошены

2017-08-15 20:18 UTC, fullstackdb commented on src/app/app.component.html
> +      <a md-button routerLink="/login" *ngIf="!user"><md-icon>account_circle</md-icon> &nbsp; Вход</a>
- Убрать &nbsp; реализовать даное поведение через  css
- Использовать елемент button для кнопок
- попробовать использовать *ngIf / else с ng-template  https://medium.com/aviabird/ngif-else-lands-in-angular-2-0-a242940e54ff


касаеться всех подобных мест

2017-08-15 20:18 UTC, fullstackdb commented on src/app/app.component.ts
>      { path: '/favorites', icon: 'star', label: 'Избранные'}
переместить значения в сервис и тянуть их динамически (использовать Observable)

2017-08-15 20:18 UTC, fullstackdb commented on src/app/app.module.ts
> +  ],
совет:

так как апликейшен вырос попробуйте разбить его на модули , так делаеться в реальном приложении

2017-08-15 20:18 UTC, fullstackdb commented on src/app/film/film-add/film-add.component.css
> +    margin-bottom: 16px;
совет:

попробуйте использовать scss

2017-08-15 20:18 UTC, fullstackdb commented on src/app/film/film-add/film-add.component.html
> +      <button md-button type="submit" color="primary" [disabled]="newFilm.invalid">Создать фильм</button>
совет:

попробуйте подключить i18n https://angular.io/guide/i18n

2017-08-15 20:18 UTC, fullstackdb commented on src/app/film/film-add/film-add.component.spec.ts
> +    expect(component).toBeTruthy();
совет:
попробуйте написать собственные тесты
http://blog.bausov.pro/tdd-bdd-tests/

2017-08-17 06:17 UTC, Melifarowow commented on src/app/app.component.ts
>      { path: '/favorites', icon: 'star', label: 'Избранные'}
переименовал в SSOService CurrentUserChanged$ на CurrentUser$. вместо подписки и дублирования user в шаблоне проверяем на логин так *ngIf='ssoService.CurrentUser$ | async'. Так можно или надо было оставить CurrentUserChanged$ и создать отдельного пользователя?

2017-08-17 06:35 UTC, Melifarowow commented on src/app/app.component.html
> +      <a md-button routerLink="/login" *ngIf="!user"><md-icon>account_circle</md-icon> &nbsp; Вход</a>
Что убрать и исполозовать css не понял
использовал ngIf / else для кнопки

2017-08-17 07:23 UTC, Melifarowow commented on src/app/app.module.ts
> +  ],
разбил на FilmsModule и PersonsModule. Т.к. FilmCard и PersonCard нам нужен практически во всех компонентах перенес их в папку shared. Так ок или есть более оптимальный вариант?

2017-08-17 19:04 UTC, Melifarowow commented on src/app/app.component.ts
>      { path: '/favorites', icon: 'star', label: 'Избранные'}
Этот момет обсуждали на разборе дз в самом конце. Подскажите какой вариант оптимальный

2017-08-18 09:17 UTC, Melifarowow commented
Хотелось бы услышать комментарий по поводу ErrorService, и его применения внутри resolve. Оставил комментарий в FilmDetailResolver

Также интересно по поводу LanguageService + i18n

По поводу SSOService писал выше и разбирали в дз, тоже есть вопросы - скорее всего я вас не так понял

2017-08-21 18:52 UTC, fullstackdb commented on src/app/app.module.ts
> +  ],
так лучше

2017-08-21 19:06 UTC, fullstackdb commented
По поводу i18n,
хорошо что разобрались как подключить и использовать. 
Также советую посмотерть как реализована работа с валютами, падежами, родами.

ErrorService выглядит неплохо

2017-08-21 19:07 UTC, fullstackdb approved these changes

2017-08-22 04:26 UTC, merged